spring:
  application:
    name: springsecuritygcp
  datasource:
    url: jdbc:h2:mem:testdb # Use 'file:~/testdb' for a file-based database
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true # Enable the H2 console
      path: /h2-console # URL path to access the console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # Auto-create/update the schema; use 'none' in production
    show-sql: true # Log SQL queries
    properties:
      hibernate:
        "[format_sql]": true
  sql:
    init:
      mode: always # Automatically initialize the database with schema/data

server:
  port: 7070
